# This file has been mostly taken verbatim from https://github.com/pymc-devs/pymc/blob/main/.github/release.yml
changelog:
  exclude:
    labels:
      - no releasenotes
  categories:
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bugfixes 🐛
      labels:
        - bug
    - title: Documentation 📖
      labels:
        - docs
    - title: Maintenance 🔧
      labels:
        - "*"
