site_name: Conjugate Models

theme:
  name: "material"
  features: 
    - navigation.indexes
  palette:
    primary: red

repo_name: Conjugate
repo_url: https://github.com/wd60622/conjugate
edit_uri: blob/main/docs/
site_url: https://wd60622.github.io/conjugate

nav:
  - Overview: index.md
  - Distributions: distributions.md
  - Models: models.md
  - Mixins: mixins.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences