site_name: Conjugate Models

theme:
  name: "material"
  custom_dir: docs/overrides
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.expand
    - navigation.top
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_name: Conjugate
repo_url: https://github.com/wd60622/conjugate
edit_uri: blob/main/docs/
site_url: https://wd60622.github.io/conjugate

extra:
  homepage: https://wd60622.github.io/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wd60622/conjugate

nav:
  - Overview: index.md
  - Modules:
    - Models: models.md
    - Distributions: distributions.md
    - Mixins: mixins.md
  - Examples:
    - Case Studies:
      - Binomial Model: examples/binomial.md
      - Bayesian Update: examples/bayesian-update.md
      - Thompson Sampling: examples/thompson.md
      - Linear Regression: examples/linear-regression.md
      - Unsupported Distributions: examples/unsupported-distributions.md
      - Inference in SQL: examples/sql.md
      - Bootstrap Comparison: examples/bootstrap.md
    - Features:
      - Plotting: examples/plotting.md
      - SciPy Distributions: examples/scipy-connection.md
      - Sampling Distributions: examples/sampling-distributions.md
      - Vectorized Operations: examples/vectorized-inputs.md
      - Indexing: examples/indexing.md
      - Generalized Numerical Inputs: examples/generalized-inputs.md
      - Scaling Distributions: examples/scaling-distributions.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
