name: Workflow for Codecov conjugate

on:
  push:
    paths:
      - "conjugate/**"
      - "pyproject.toml"
      - "tests/**"

  pull_request:
    paths:
      - "conjugate/**"
      - "pyproject.toml"
      - "tests/**"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install . pytest pytest-cov pytest-mpl pypika
      - name: Run tests and collect coverage
        run: pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.4.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
